{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.coremaker.io
  resources:
  - postgresdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.coremaker.io
  resources:
  - postgresdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.coremaker.io
  resources:
  - postgresdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgres.coremaker.io
  resources:
  - postgresschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.coremaker.io
  resources:
  - postgresschemas/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.coremaker.io
  resources:
  - postgresschemas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgres.coremaker.io
  resources:
  - postgresusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.coremaker.io
  resources:
  - postgresusers/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.coremaker.io
  resources:
  - postgresusers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgres-operator
    app.kubernetes.io/part-of: postgres-operator
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'
{{- end}}